### ISSUE TITLE
TRPO implementation

### ISSUE THREAD

**Issue by tanderberg** [rllab/rllab#14]
I am perplexed by the [TRPO implementation](https://github.com/rllab/rllab/blob/master/rllab/algos/trpo.py). It's just a wrapper around the [NPO code](https://github.com/rllab/rllab/blob/master/rllab/algos/npo.py). The [TRPO paper](http://www.jmlr.org/proceedings/papers/v37/schulman15.pdfl) does acknowledge that 

> TRPO is related to prior methods (e.g. natural policy gradient) but makes several changes, most notably by using a ﬁxed KL divergence rather than a ﬁxed penalty coefﬁcient.

but I don't see that; you use the KL divergence in the NPO code. Is there a description of the difference between your NPO and TRPO somewhere?

**Comment by dementrock** [comment]
The implementation of natural policy gradient algorithm here (and the description in the paper) differs from the traditional natural policy gradient, in that the step size is calculated differently by doing a second-order approximation to the KL divergence constraint. It also makes use of the conjugate gradient algorithm. Hence we named our implementation "truncated" natural policy gradient (TNPG).

Then, TNPG and TRPO deviates only in that TRPO performs a line search to make sure that there is sufficient decrease in the surrogate loss function. TNPG uses almost the same parameters, except that `max_backtracks=1`, which essentially does not perform backtracking (and thus no line search).

**Comment by tanderberg** [comment]
Thanks! That will teach me to read [the paper](http://arxiv.org/abs/1604.06778) before the code. :)
