### ISSUE TITLE
Problem running openai gym environment than the Pendulum

### ISSUE THREAD

**Issue by AliGhadirzadeh** [rllab/rllab#16]
Hi,

I tested the example provided to use openai gym environments. The default example works fine. But the problem is that when I test it on another environment like "CartPole-v0" I get following error message:

env = normalize(GymEnv('CartPole-v0'))
File "/home/rllab/rllab/rllab/envs/normalized_env.py", line 23, in __init__
    assert isinstance(env.action_space, Box)
AssertionError

It is worth nothing that I can run the scenario using openai gym with no problem. 

Thanks in advanced,
Ali

**Comment by dementrock** [comment]
Hi @AliGhadirzadeh, this error is because the CartPole environment in Gym uses discrete actions. You can get rid of the `normalize` call, and use a `CategoricalMLPPolicy` instead of a `GaussianMLPPolicy`, which should work.

**Comment by korymath** [comment]
Same issue here.... now running into problems with 

[2016-06-15 17:36:13,322] Making new env: Acrobot-v0
Error while instantiating <class 'rllab.exploration_strategies.gaussian_strategy.GaussianStrategy'>

File "/rllab/rllab/exploration_strategies/gaussian_strategy.py", line 13, in __init__
    assert isinstance(env_spec.action_space, Box)
AssertionError

Thoughts?

**Comment by dementrock** [comment]
@korymath DDPG unfortunately only works with continuous actions, at least in the way it is currently setup. In environments with discrete actions, DQN might be a better choice. rllab unfortunately doesn't have an implementation of DQN at the moment due to its emphasis on continuous control, but there seems to be some other implementations available e.g. https://github.com/sherjilozair/dqn

**Comment by korymath** [comment]
Awesome, thank you kindly for the quick reply. Okay, I understand what you
are saying, the action space is discrete in those domains... that is what I
imagined as the difference between CartPole and InvertedPendulum and that
is what seems to be the case.

On Wed, Jun 15, 2016 at 8:58 PM, Rocky Duan <notifications@github.com>
wrote:

> @korymath <https://github.com/korymath> DDPG unfortunately only works
> with continuous actions, at least in the way it is currently setup. In
> environments with discrete actions, DQN might be a better choice. rllab
> unfortunately doesn't have an implementation of DQN at the moment due to
> its emphasis on continuous control, but there seems to be some other
> implementations available e.g. https://github.com/sherjilozair/dqn
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rllab/rllab/issues/16#issuecomment-226382548>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAK3sy73XHMqDmnvDnGYcO9EC5hqyhlqks5qMMnsgaJpZM4I2Tgi>
> .
>



-- 
____________________________
Kory Mathewson

**Comment by AliGhadirzadeh** [comment]
Thanks for your support. It works now.

**Comment by dementrock** [comment]
Ok, awesome!
