### ISSUE TITLE
specifying initial weights to mlp policy

### ISSUE THREAD

**Issue by alexbeloi** [rllab/rllab#19]
Is there a way you could expose the weight initialization for the MLP in policies use it (e.g. GaussianMLPPolicy).

I have weights that have been trained in a supervised setting with which I would like to initialize a policy.

**Comment by dementrock** [comment]
Hi @alexbeloi,

Can you describe some more details? Are you pretraining the entire set of weights or only specific layers?

**Comment by alexbeloi** [comment]
Hi @dementrock,

Thank you for your help. I'm pretraining an entire set of weights (entire MLP network) in a related setting and I would like to initialize the mean network of the GaussianMLPPolicy as using all the weights from all the layers in the pretrained network.

**Comment by dementrock** [comment]
Do you have a proposed interface for doing this? My current feeling is that this would be a bit application-specific, e.g. a different way to do this would be to only pretrain the first few layers, and initialize the rest.

**Comment by dementrock** [comment]
In principle you should be able to write a few lines of code to wrap this functionality, since the policy constructor takes a `mean_network` parameter, which could be your custom-initialized MLP.

**Comment by alexbeloi** [comment]
Unless I'm misunderstanding, it looks to me as though only CategoricalMLPPolicy takes a parameter (prob_network) to initialize its MLP network.

For example the constructor for GaussianMLPPolicy doesn't have a mean_network or std_network parameter or the like. It does have a std_share_network parameter which doesn't appear to do anything.

I could write a few lines to as you described, I just didn't want to get stuck behind the upstream master branch. If it's agreeable, I can try to write a minimal refactoring and make a pull request, then you can see if it is sufficiently clean for your future plans with this project.

**Comment by alexbeloi** [comment]
Actually, I just noticed that you have a GaussianMLPRegressor. I'll just use that to do my supervised training, then transfer its mean/std networks to the GaussianMLPPolicy.

Thanks for your active interaction. Apologies for the sudden inundation of requests from me ;-)
