### ISSUE TITLE
baseline problem in the vanilla policy gradient example

### ISSUE THREAD

**Issue by flyers** [rllab/rllab#2]
Hi everyone,
When I am running the rllab/examples/vpg_2.py example, I found that the baseline is actually a zero vector. It seems that we need to explicitly call the baseline.fit method before calling the baseline.predict method. @dementrock 
Thanks.

**Comment by flyers** [comment]
@dementrock

**Comment by dementrock** [comment]
Ahh yes. Your interpretation is correct & thanks for reporting the issue! I will push a fix to the master branch shortly.
