### ISSUE TITLE
Request: save/resume training

### ISSUE THREAD

**Issue by 123mitnik** [rllab/rllab#25]
how difficult would be to implement:
  - save training progress
  - load training progress and continue training
  - load training progress and test (no training)

**Comment by dementrock** [comment]
Hi @123mitnik,

Right now the first and last are supported already. By default, if you run experiment in "stub" mode (i.e. calling `stub(globals())` and then running experiment via `run_experiment_lite`, it should be saving pickle files under the data directory. Then, you can run `python scripts/sim_policy.py PKL_FILE` to replay the trained policy.

Which algorithm(s) do you need the resume training feature for? I can give a shot at implementing a primitive version.

**Comment by 123mitnik** [comment]
the main focus is on Trust Region Policy Optimization and second on the list is Truncated Natural Policy Gradient
my homebrew env is doing some time consuming tasks and it will take huge amounts of time to finish the training end to end

it will be great asset if you can resume the policy training .. just a lifesaver in demanding envs

I would like to Thank You for your fast replay. And to appreciate how wonderful rllab is !

**Comment by dementrock** [comment]
Hi @123mitnik, I've pushed an experimental implementation.

For new experiment runs, now the snapshot files (ending in `.pkl`) will store a serialized version of the `Algorithm` object. Then, you can resume training by running

```bash
python scripts/resume_training.py PATH_TO_PKL_FILE
```

**Comment by 123mitnik** [comment]
wow !!! that was FAST

Thank You so much !!! ... will start using it immediately
