### ISSUE TITLE
Normalized the discrete action space

### ISSUE THREAD

**Issue by markovyao** [rllab/rllab#4]
the code in  ''normalized_env.py''  did not implement the  Normalized  discrete action space

**Comment by dementrock** [comment]
How would you define normalizing discrete action spaces?

**Comment by markovyao** [comment]
Ok，  my fault.
''normalized_env.py''  assert  isinstance(env.action_space, Box)  
If  we  use a  discrete action_space，  how  to  rewrite the scripts?

**Comment by dementrock** [comment]
Are you using features other than normalizing the actions? I've realized that it does implement a couple features that make sense for discrete actions too, e.g. normalizing observations and rewards.

One option is just to make it a no-op for discrete actions.

**Comment by dementrock** [comment]
@markovyao Any updates on this issue?
