### ISSUE TITLE
run trop_cartpole_stub fails

### ISSUE THREAD

**Issue by Alex-zhai** [rllab/rllab#9]
![ii 9g0vsu7 zxmf 46y p3](https://cloud.githubusercontent.com/assets/11607954/15562362/22cfb76a-2331-11e6-9975-6e246dadc87d.png)

when I ran trop_cartpole_stub.py , I got nothing except using seed 1 ,using seed 1. My env is Ubantu 14.04 gpu:gtx970 cuda:7.5 .

**Comment by dementrock** [comment]
Hi @Alex-zhai, can you Ctrl-C the program and paste a stacktrace to show where it's stuck?

**Comment by Alex-zhai** [comment]
I downloaded the lastest version of rllab, and everything is OK now.Thank you for your reply.

**Comment by dementrock** [comment]
Ok, sounds good!
